//@version=6 
indicator(title="EMA_Comb", overlay=true)

// The first one diagram for three EMA
// Three line can check for the 15M, 30M, 1H
// If yellow line at the top, maybe you can do "buy"
// If blue line at the top, maybe you can do "sell"
// Before operating. check the 4H, (1D) direction
// Any questions to ask Agent M

ema1_1 = ta.ema(close, 5)
ema1_2 = ta.ema(close, 10)
ema1_3 = ta.ema(close, 20)

plot(ema1_1, color = color.rgb(156, 155, 67))
plot(ema1_2, color = color.rgb(46, 173, 116))
plot(ema1_3, color = color.rgb(68, 0, 255))

// The second diagram for two EMA
// Two line can do the short contract
// Like above recognizing
// Try to check at 5M, 15M
// Check the 1H, 4H

ema2_1 = ta.ema(close, 5)
ema2_2 = ta.ema(close, 12 )

plot(ema2_1, color = color.rgb(78, 188, 109, 0.75))
plot(ema2_2, color = color.rgb(210, 133, 255, 0.75))

// The third EMA for strategy 
// Same as above
// Red line is long time frame
// Blue line is short
// Yellow line to do the test

ema3_1 = ta.ema(close, 144)
ema3_2 = ta.ema(close, 169)
ema3_3 = ta.ema(close, 576)
ema3_4 = ta.ema(close, 676)
ema3_5 = ta.ema(close, 12)

transp = bar_index % 2 < 1 ? 75 : 25
plot(ema1, title="EMA1", color=color.rgb(68, 149, 215, transp), linewidth=2)
plot(ema2, title="EMA2", color=color.rgb(68, 149, 215, transp), linewidth=2)
plot(ema3, title="EMA3", color=color.rgb(220, 57 ,30, transp), linewidth=2)
plot(ema4, title="EMA4", color=color.rgb(220, 57 ,30, transp), linewidth=2)
plot(ema5, title="EMA5", color=color.rgb(240, 220, 31, transp), linewidth=2)
